#!/bin/bash

OUT_DIR="/dev/shm/"
OUT_FILE="many-to-one-output"
cleanerFile="cleaner$(date +%Y%m%d%H%M%S).sh"

function showHelp() {
    echo "Usage: $0 -d [outDir] -o [outFile] [FILE]..."
    exit
}

while getopts "d:o:h" Option
do                                                                                
    case $Option in                                                                   
        d)
            OUT_DIR=${OPTARG};;
        o)
            OUT_FILE=${OPTARG};;
        h)
            showHelp;;
        *)
            exit;;
    esac                                                                              
done
shift $((OPTIND-1))

if [ $# -lt 2 ]
then
    echo "less than 2 files, exit now"
    exit
fi

OUT_NAME=${OUT_DIR}$OUT_FILE
mkfifo $OUT_NAME
cat $* > $OUT_NAME &

cat<<EOF>$cleanerFile
#!/bin/bash

rm $OUT_NAME
rm -- "\$0"
EOF
chmod +x $cleanerFile

echo "created $OUT_NAME"
echo "remember to clean environment using $cleanerFile"
